version: "3.3"

services:
    server:
        image: server:latest
        build: ./
        ports: 
        - 52200:52200
        deploy:
            replicas: 3
            restart_policy:
                condition: on-failure